# Site settings
title: çŠè’‚æ–¯Â·ç¾½æœˆğŸ’„  #ä½ åšå®¢çš„æ ‡é¢˜
SEOTitle: Shandris Feathermoon | ç‰›åŸè™å¦  #æ˜¾ç¤ºåœ¨æµè§ˆå™¨ä¸Šæœç´¢çš„æ—¶å€™æ˜¾ç¤ºçš„æ ‡é¢˜
header-img: img/post-bg-swift.webp #æ˜¾ç¤ºåœ¨é¦–é¡µçš„èƒŒæ™¯å›¾ç‰‡
email: info@tebangtech.com
description: "Heyï¼Œæˆ‘æ˜¯éœğŸ’„ï¼Œå¤–è²Œåä¼š, è¿™æ˜¯æˆ‘Fork FeDemoçš„åˆ©ç”¨ GitHub Pages ä¸ Jekyll æ­å»ºçš„ä¸ªäººåšå®¢ã€‚çº¯æ¨¡æ¿æ­å»ºï¼Œä¸ä¼šå†™ä»£ç ,æ¬¢è¿å¤§å®¶æ¥ç©ã€‚" #ç½‘ç«™ä»‹ç»
keyword: "ç‰›åŸè™å¦,å¤–è´¸,GitHub,ä¸ªäººæ—¥è®°,åšå®¢,Blog,WhatsApp" #å…³é”®è¯
url: "https://huijingfei.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "blog" # you code repository
author: éœğŸ’„

# æ˜¯å¦æ‰˜ç®¡åœ¨Coding_Pages
Coding_Pages: true

#  æ˜¯å¦å¼€å¯ç™¾åº¦è‡ªåŠ¨æ¨é€JSä»£ç 
baidu_js_push: false

# Sidebar settingsä¾§è¾¹æ 
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Elune be with you!"
sidebar-avatar: /img/avatar_p11179162.webp      # use absolute URL, seeing it's used in both `/` and `/about/`


# SNS settingsç¤¾äº¤è´¦å·
RSS: false
weibo_username:    huijingfei
zhihu_username:    huijingfei
github_username:    huijingfei
facebook_username:    tebangtech
twitter_username:   TebangTech
instagram_username:   rotherhamsalon
email: info@tebangtech.com

# coding_username: huijingfei



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# gems: [jekyll-paginate]
plugins: [jekyll-paginate]
gems: [jekyll-sitemap] 



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important


# è¯„è®ºç³»ç»Ÿ
# Gitalk
gitalk:
  enable: true    #æ˜¯å¦å¼€å¯Gitalkè¯„è®º
  clientID: 'e47b65b2519223baf50e'    #ç”Ÿæˆçš„clientID
  clientSecret: '97c1f4e6977085d5017928087821059bc102325a'   #åŒä¸Š
  repo: Blog_Gitalk    #ä»“åº“åç§°
  owner: huijingfei    #githubç”¨æˆ·å
  admin: huijingfei




# Analytics settings ç™¾åº¦ç»Ÿè®¡track_id
# Baidu Analytics
ba_track_id: 

# Google Analytics
# ga_track_id: ''            # Format: UA-xxxxxx-xx
# ga_domain: auto





# Featured Tags
featured-tags: true                     # æ˜¯å¦ä½¿ç”¨é¦–é¡µæ ‡ç­¾
featured-condition-size: 1              # ç›¸åŒæ ‡ç­¾æ•°é‡å¤§äºè¿™ä¸ªæ•°ï¼Œæ‰ä¼šå‡ºç°åœ¨é¦–é¡µ

#search plugins
search: true                            # æ˜¯å¦ä½¿ç”¨æœç´¢æ’ä»¶

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true


# è‡ªåŠ¨ç”Ÿæˆsitemap
sitemap:
    path: sitemap.xml


# Friendså¥½å‹é“¾æ¥
friends: [
    {
        title: "Tebang Tech",
        href: "https://tebangtech.com/"
    },{
        title: "Creative Touch",
        href: "https://www.creativetouchrotherham.co.uk/"
    },{
        title: "Messi Biology",
        href: "https://meixi-mgo.com/"
    },{
        title: "Blogger post",
        href: "https://huijingfei.blogspot.com/"
    },{
        title: "Tibet Mag",
        href: "https://tibetmag.com/"
    },{
        title: "Majing Carpet",
        href: "https://majcarpet.com/"
    }
]
